# Datasets Concatenation

In [13]:
import pandas as pd 
import dask.dataframe as dd

In [14]:
# read csv from multiple folders 
df = dd.read_csv("../cleaned_data/mhc-i/*.csv")

In [15]:
df.compute()

,start,end,length,peptide,score,accession_code,protein_length,antigen_presenting_protein
0,204.0,212.0,9.0,KSWLVHKQW,NaN,MN959467,495,MHC-I
1,313.0,321.0,9.0,AETQHGTVL,NaN,MN959467,495,MHC-I
2,204.0,212.0,9.0,KSWLVHKQW,NaN,MN959467,495,MHC-I
3,49.0,57.0,9.0,EVTNPAVLR,NaN,MN959467,495,MHC-I
4,223.0,231.0,9.0,GASTSQETW,NaN,MN959467,495,MHC-I
...,...,...,...,...,...,...,...,...
4732,3.0,11.0,9.0,CVGIGNRDF,NaN,MT862870,495,MHC-I
4733,57.0,65.0,9.0,RKLCIEAKI,NaN,MT862870,495,MHC-I
4734,124.0,132.0,9.0,KLEGKIVQY,NaN,MT862870,495,MHC-I
4735,124.0,132.0,9.0,KLEGKIVQY,NaN,MT862870,495,MHC-I
4736,3.0,NaN,NaN,NaN,NaN,MT862870,495,MHC-I

In [18]:
# convert into pandas df 
df = df.compute()

In [19]:
# save 
df.to_csv('../cleaned_data/mhc-i/mhc-i_prediction.csv', index=False)

In [20]:
df = dd.read_csv('../old/mhc-i/*/*.csv')

In [21]:
df.compute()

,allele,seq_num,start,end,length,peptide,core,icore,score,rank
0,HLA-A*68:01,1,353,361,9,TVNPIVTEK,TVNPIVTEK,TVNPIVTEK,0.988490,0.01
1,HLA-A*01:01,1,170,178,9,TTEAELTGY,TTEAELTGY,TTEAELTGY,0.970718,0.01
2,HLA-A*02:06,1,346,354,9,HVLGRLITV,HVLGRLITV,HVLGRLITV,0.963628,0.01
3,HLA-A*03:01,1,353,361,9,TVNPIVTEK,TVNPIVTEK,TVNPIVTEK,0.959310,0.01
4,HLA-A*68:01,1,49,57,9,EAKQPATLR,EAKQPATLR,EAKQPATLR,0.933492,0.05
...,...,...,...,...,...,...,...,...,...,...
2545,HLA-C*08:02,1,118,126,9,MFTCKKNME,MFTCKKNME,MFTCKKNME,0.000000,100.00
2546,HLA-C*08:02,1,104,112,9,GCGLFGKGG,GCGLFGKGG,GCGLFGKGG,0.000000,100.00
2547,HLA-C*08:02,1,98,106,9,DRGWGNGCG,DRGWGNGCG,DRGWGNGCG,0.000000,100.00
2548,HLA-C*08:02,1,92,100,9,CKHSMVDRG,CKHSMVDRG,CKHSMVDRG,0.000000,100.00
2549,HLA-C*08:02,1,87,95,9,DKRFICKHS,DKRFICKHS,DKRFICKHS,0.000000,100.00

In [22]:
df.map_partitions(len).compute()

0      4870
1      4383
2      4870
3      2922
4      4870
       ...
100    1386
101    4250
102    3825
103    4250
104    2550
Length: 105, dtype: int64

In [26]:
df = df.compute()

In [27]:
df.shape

(443728, 10)